export enum PostActionTypes {
  ADD_POST = "ADD_POST",
  REMOVE_POST = "REMOVE_POST",
  FETCH_POST_REQUEST = "FETCH_POST_REQUEST",
  FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS",
  FETCH_POST_FAILED = "FETCH_POST_FAILED",
}
